name = input("What is your name? ")
age = input(f"How old are you, {name} ? ")
print(f"Hello, {name}! Your age is {age}, right?")
num = int(input("Enter your lucky number: "))
print(f"{num} is a really lucky number! ")
color = input("your favorite color: ")
print(f"{color}  is beautiful color,Lovely,{name}!")
